### ISSUE TITLE
Failed on LEDAssembly, dave20874

### ISSUE THREAD

**Issue by DaveOfThings** [Jnesselr/fusion-360-total-exporter#1]
At "Writing data!, Project: 12 of 28, Writing design 8 of 18",
Failed while working on d:/fusion 360 export\Hub David Wheeler\Project LED Sign\LED Sign\LED Assembly.f3d
<img width="292" alt="Fusion 360 Traceback" src="https://user-images.githubusercontent.com/8674700/93536400-e6808300-f916-11ea-9a31-0ec408284e3a.PNG">

Note: some components were out of date in this assembly.

**Comment by Jnesselr** [comment]
Can you list out what components you have in that file? I think there's some character that's not file path safe in one of your component names. I did replace '/' with a space and I'll probably have to do that here too, but I'll need to know what character it's unhappy with first. It looks like it's a component just under your root component.

**Comment by DaveOfThings** [comment]
It's probably 'round 7/8" spacer', then.  (Note double quotes in the component name.)  That's a component I imported via McMaster.

**Comment by DaveOfThings** [comment]
<img width="1281" alt="Screen" src="https://user-images.githubusercontent.com/8674700/93537279-1af53e80-f919-11ea-88a4-8f60d7dc0ea8.PNG">

**Comment by Jnesselr** [comment]
Oh yeah, that'll do it!

**Comment by Jnesselr** [comment]
Thanks for reporting! You should be able to do a "git pull" and that'll be fixed.

Let me know if you have any other issues. Awesome looking design by the way!

**Comment by DaveOfThings** [comment]
Yeah, that did it!  Thanks, it was my first Fusion 360 assembly but two years later I still haven't built the actual thing.  :-(

**Comment by Jnesselr** [comment]
I actually have one from a couple of years back that I didn't build and it's the one I used to test that broken / out of date assemblies still get exported.
