### ISSUE TITLE
Skip by josephduchesne

### ISSUE THREAD

**Issue by 3d-gussner** [Jnesselr/fusion-360-total-exporter#13]
Didn't look if it works but I think something like this could be a good addition to this project.

https://github.com/josephduchesne/fusion-360-total-exporter/commit/b3ac05d90c5226ed5166d0c85113bbf3d5513254

I just had an error (forgot to make a screenshot or copy) and had to start from the beginning.

**Comment by 3d-gussner** [comment]
Rerun the script after fresh git pull (and with the skip merged) and got same error.
![Error#1](https://user-images.githubusercontent.com/25530011/93661354-6ca3e300-fa57-11ea-8302-0506f3dd7615.JPG)

Had to restart Fusion360 to I guess "reload" the script after the `git pull` and `git merge`

You should consider to mention this in the README that updating the script needs a Fusion360 restart.

**Comment by Gnindit** [comment]
I just edited the py file while fusion was open and ran the script again and it seemed to have made the changes I wrote in the file.

**Comment by 3d-gussner** [comment]
It looks like the skipping function doesn't work...Still see existing some files being recreated.
But it is faster after restart and continues writing.

**Comment by Jnesselr** [comment]
The current master branch will still go through all files, but will skip re-creating stp, stl, igs, and dxf files if they already exist.

**Comment by 3d-gussner** [comment]
It would be also great if the f3d file isn't created if it is existing. Only issue I can see is that it might be created but not finished while Fusion360 crashes.
And with me it crashes a lot (guess RAM issues)
