### ISSUE TITLE
Failed, see screenshots

### ISSUE THREAD

**Issue by aaronjasso** [Jnesselr/fusion-360-total-exporter#16]
Successfully exported five (of 53 total) projects, then failed on the sixth.

![image](https://user-images.githubusercontent.com/22285225/93670004-7597b300-fa5d-11ea-951c-7dfabf7a21a5.png)

![image](https://user-images.githubusercontent.com/22285225/93670005-7a5c6700-fa5d-11ea-8c18-0f25f94c17cc.png)

I can upload the file if it'll help.

THANK YOU for making this, BTW. I hope I can get it to work.
-Aaron

**Comment by Gnindit** [comment]
This is already mentioned in earlier thread. 
You can try this, it help me get further.

https://github.com/Jnesselr/fusion-360-total-exporter/pull/14/commits/fb1ea8610d0304cdc88f85a242e7f71c34025239

**Comment by 3d-gussner** [comment]
Please also check https://github.com/Jnesselr/fusion-360-total-exporter/issues/4
I had to enable NTFS Long paths

**Comment by Jnesselr** [comment]
Should be fixed with #18. Reopen the issue if it isn't please.

**Comment by aaronjasso** [comment]
> 
> 
> This is already mentioned in earlier thread.
> You can try this, it help me get further.
> 
> [fb1ea86](https://github.com/Jnesselr/fusion-360-total-exporter/commit/fb1ea8610d0304cdc88f85a242e7f71c34025239)

This is working so far. Thank you!

**Comment by Jnesselr** [comment]
@aaronjasso Feel free to run the version from the master branch as it has that fix in place.
