### ISSUE TITLE
Models with Invalid characters for Windows filenames causes the script to fail.

### ISSUE THREAD

**Issue by pinski1** [Jnesselr/fusion-360-total-exporter#23]
Related to #22 

If the model name contains ones of the characters that are invalid for a windows file name the script crashes:
        < (less than)
        > (greater than)
        : (colon)
        " (double quote)
        / (forward slash)
        \ (backslash)
        | (vertical bar or pipe)
        ? (question mark)
        * (asterisk)

e.g. I had a gearbox which had the string "1:4.25" in the name, when I tried to manually export the stp/igs/stl/f3d the name field would appear empty and the export would fail as the script would try to export a nameless file.

**Comment by pinski1** [comment]
possible fix:
1. copy the name from the elements
2. overwrite invalid characters with "_"
3. use as an alternative name if name field is empty

**Comment by Jnesselr** [comment]
The current version should already replace all of those characters with a space in the `_name` function. Is it not doing that? I don't think I understand this issue.

**Comment by pinski1** [comment]
Ah, sorry then, I think this was against an older version. It's hard for me to repeatably test as I'm trying to pull out ~900 models.

Thanks for your script.
