### ISSUE TITLE
Script hangs after exporting some number of projects

### ISSUE THREAD

**Issue by moriraaca** [Jnesselr/fusion-360-total-exporter#45]
The script has worked ok ~6mths ago, but a few days ago when I was trying to do the export it suddenly froze (together with F360, killing the application is required). I've re-run it, and it was consistently freezing at the same project. I thought the project is bad, but when I've tweaked the script to export only that project it worked - and when I've excluded that particular project it still froze, only later.

I've spent quite a lot of time debugging the issue, and while I still don't know the root cause, it seems that the script freezes after exporting some number of projects/documents/files - I haven't been able to pinpoint what exactly, but definitely something breaks consistently, and it's related to the amount of exported things. The script hangs in line https://github.com/Jnesselr/fusion-360-total-exporter/blob/master/Fusion%20360%20Total%20Export.py#L138, apparently it tries to open a file but the call never ends.

I'm not attaching the `output.log` as it doesn't have any useful info. There are no errors, every log line looks ok, and then suddenly there's a line `2023-05-24 05:36:21,052 - INFO - Exporting file "<file name>"` - and that's it, no further data. With strategically placed debugging `self.log.info('HERE!")` I've managed to establish that the line 138 is the culprit, but why - I don't know.

There's a workaround, I've added this piece of code after line https://github.com/Jnesselr/fusion-360-total-exporter/blob/master/Fusion%20360%20Total%20Export.py#L75:

```python
        # Fix for the problem with freezing export - set project_start to whatever was the last freeze on 
        project_start = 0
        if project_index < project_start:
          continue
```

With that in place, I start the export; it fails (hangs) at project e.g. 6; I change the `project_start` variable manually to `6` and re-start the export; first 6 projects are ignored, and we start exporting from number 6 onward; Then it freezes again (but later), so I repeat this until all files are exported. Ugly? Sure - but I've already spent too much time debugging, and I don't have hundreds of projects, so currently this manual workaround works for me.

I'm mostly posting this here for others, as I don't think this will be fixed, but hey you never know :-) btw big thanks to the author, this script is a lifesaver!

**Comment by Jnesselr** [comment]
I haven't had time to work on this, but please check out #46 and see if that works for you.
