### ISSUE TITLE
Tried to run in FreeCAD and failed

### ISSUE THREAD

**Issue by TinkerJim** [Jnesselr/fusion-360-total-exporter#48]
Hello!

I just ran your script from a link in FreeCAD 0.21.2 and got the following failure messages in the Report View.

Please advise.

17:51:54  (js) Uncaught SyntaxError: Failed to execute 'matches' on 'Element': ':modal' is not a valid selector.
17:51:55  (js) Uncaught SyntaxError: Failed to execute 'matches' on 'Element': ':modal' is not a valid selector.
17:51:55  (js) Uncaught (in promise) TypeError: this.styledInputContent.replaceChildren is not a function
17:51:55  (js) Uncaught (in promise) TypeError: this.styledInputContent.replaceChildren is not a function
17:51:55  (js) TypeError: e.replaceAll is not a function
17:51:55  (js) Uncaught TypeError: e.replaceAll is not a function
17:52:18  (js) TypeError: e.replaceAll is not a function
17:52:18  (js) Uncaught TypeError: e.replaceAll is not a function
17:52:18  (js) Uncaught (in promise) TypeError: t.replaceChildren is not a function
17:52:38  (js) Uncaught (in promise) TypeError: t.replaceChildren is not a function

**Comment by Jnesselr** [comment]
A few things:
- This project should be archived. I'll do that after commenting here. It doesn't work anymore and I don't plan to maintain it any longer.
- This is designed for fusion360 and is python, not Javascript like FreeCAD expects.
