### ISSUE TITLE
Fails with project names/file names with special characters in them (* in my case)

### ISSUE THREAD

**Issue by munchj** [Jnesselr/fusion-360-total-exporter#7]
Thanks a lot for this script though ! Very helpful

**Comment by Gnindit** [comment]
I have the same problem with naming files with "*" (ASCII 42).
![image](https://user-images.githubusercontent.com/17782127/93616204-b5668800-f9d4-11ea-99e6-ffa387ff8acc.png)
The OSError: line is in Swedish and says something like Wrong syntax for file name, folder name or volume label.

**Comment by Gnindit** [comment]
Maybe just have to add
.replace('*', ' ')
on line 198.

-return name.replace('/', ' ').replace('"', ' ').replace('%', ' ')
+return name.replace('/', ' ').replace('"', ' ').replace('%', ' ').replace('*', ' ')

I will try now.

**Comment by Jnesselr** [comment]
That sounds correct. If that works, please submit a pull request.

**Comment by Gnindit** [comment]
Seems to work.
Sorry have no idea how to submit a pull request so please feel free to fix this.
